import { chromium } from 'playwright-core';
const DIR = '/private/tmp/claude-501/-Users-hanjiho-Documents------2/390669f3-de7b-486a-9a1b-e35faf92d581/scratchpad';
const b = await chromium.launch({ channel: 'chrome', headless: true });
const page = await (await b.newContext({ viewport: { width: 420, height: 1400 }, deviceScaleFactor: 2 })).newPage();
page.on('dialog', (d) => d.accept());
await page.goto('http://localhost:4183/', { waitUntil: 'networkidle' });
await page.evaluate(() => localStorage.clear());
await page.reload({ waitUntil: 'networkidle' });
await page.getByRole('button', { name: /좋아요, 시작할게요/ }).click();
await page.locator('input[type="text"]').fill('한지호');
await page.getByRole('button', { name: /초수 \(교대 4학년\)/ }).click();
await page.getByRole('button', { name: '다음', exact: true }).click();
await page.getByRole('button', { name: '다음', exact: true }).click();
await page.getByRole('button', { name: '부산', exact: true }).click();
await page.getByRole('button', { name: /시작하기/ }).click();
await page.waitForTimeout(1600);
await page.getByRole('button', { name: '설정' }).first().click();
await page.waitForTimeout(900);
const card = page.locator('section').filter({ hasText: '데모 모드' }).first();
await card.scrollIntoViewIfNeeded();
await page.waitForTimeout(400);
await card.screenshot({ path: `${DIR}/t2-toggle-off.png` });
await page.getByRole('switch', { name: '데모 모드' }).click();
await page.waitForTimeout(5000);
await page.getByRole('button', { name: '설정' }).first().click();
await page.waitForTimeout(1000);
const card2 = page.locator('section').filter({ hasText: '데모 모드' }).first();
await card2.scrollIntoViewIfNeeded();
await page.waitForTimeout(400);
await card2.screenshot({ path: `${DIR}/t3-toggle-on.png` });
await page.getByRole('button', { name: '데모 모드' }).last().click();
await page.waitForTimeout(500);
await page.screenshot({ path: `${DIR}/t4-panel.png` });
await b.close();
